export type Lang = 'ar' | 'en'

export const translations = {
  ar: {
    // Navigation
    nav_home: 'الرئيسية',
    nav_learn: 'اعرفي أكثر',
    nav_signs: 'علامات تستحق الانتباه',
    nav_detection: 'الكشف المبكر',
    nav_prevention: 'الوقاية',
    nav_journey: 'رحلة العلاج',
    nav_reconstruction: 'إعادة بناء الثدي',
    nav_saudi: 'في السعودية',
    nav_faq: 'أسئلة شائعة',
    nav_start: 'ابدئي الآن',
    nav_lang: 'English',

    // Hero
    hero_badge: 'أكتوبر | شهر التوعية بسرطان الثدي',
    hero_headline_1: 'الوعي',
    hero_headline_2: 'بداية الأمل',
    hero_sub: 'سرطان الثدي من أكثر السرطانات شيوعًا بين النساء في المملكة، لكن اكتشافه مبكرًا يمكن أن يصنع فرقًا كبيرًا في رحلة العلاج.',
    hero_cta1: 'تعرّفي على الكشف المبكر',
    hero_cta2: 'اكتشفي العلامات المهمة',
    hero_fact1: 'الاكتشاف المبكر يُحدث فرقًا',
    hero_fact2: 'الوعي يبدأ بالمعرفة',
    hero_fact3: 'لستِ وحدك',

    // Explore section
    explore_title: 'من أين نبدأ؟',
    explore_sub: 'اختاري الموضوع الذي تريدين معرفته أكثر',
    explore_read_more: 'اعرفي أكثر',

    // Explore cards
    card1_emoji: '🎀',
    card1_title: 'ما هو سرطان الثدي؟',
    card1_desc: 'فهم المرض بشكل بسيط وواضح',
    card2_emoji: '🔎',
    card2_title: 'علامات تستحق الانتباه',
    card2_desc: 'تعرّفي على التغيرات التي قد تستحق التقييم',
    card3_emoji: '🩷',
    card3_title: 'الكشف المبكر',
    card3_desc: 'لماذا يهم التوقيت في التشخيص',
    card4_emoji: '🌿',
    card4_title: 'تقليل عوامل الخطورة',
    card4_desc: 'عادات صحية قد تساعد على تقليل المخاطر',
    card5_emoji: '🤍',
    card5_title: 'رحلة العلاج والتعافي',
    card5_desc: 'من التشخيص إلى الحياة بعد العلاج',
    card6_emoji: '🌸',
    card6_title: 'إعادة بناء الثدي',
    card6_desc: 'خيارات إعادة البناء بعد الجراحة',

    // What is breast cancer page
    whatIs_title: 'ما هو سرطان الثدي؟',
    whatIs_body: 'سرطان الثدي هو نمو غير طبيعي لخلايا الثدي. وقد يبدأ في أنسجة الثدي، ومع تطور المرض قد ينتشر إلى العقد اللمفاوية أو أعضاء أخرى.',
    whatIs_body2: 'يُعدّ سرطان الثدي من أكثر السرطانات شيوعًا عالميًا بين النساء، وكذلك في المملكة العربية السعودية. ويمكن أن يصيب الرجال أيضًا، وإن كان أقل شيوعًا.',
    whatIs_anatomy_title: 'تعرّفي على تشريح الثدي',
    whatIs_anatomy_sub: 'انقري على كل منطقة لمعرفة المزيد',
    whatIs_note: 'وجود كتلة لا يعني بالضرورة وجود سرطان، لكن أي تغير جديد أو غير معتاد يستحق التقييم الطبي.',
    anatomy_tissue: 'نسيج الثدي',
    anatomy_tissue_desc: 'نسيج الثدي يتكون من الغدد الثديية والأنسجة الدهنية والضامة. تبدأ معظم أنواع سرطان الثدي في هذه الأنسجة.',
    anatomy_ducts: 'القنوات',
    anatomy_ducts_desc: 'القنوات هي الممرات التي ينتقل فيها الحليب من الغدد إلى الحلمة. يُعدّ سرطان القنوات (Ductal Carcinoma) من أكثر أنواع سرطان الثدي شيوعًا.',
    anatomy_nipple: 'الحلمة',
    anatomy_nipple_desc: 'قد تظهر تغيرات في الحلمة كانقلابها أو ظهور إفرازات غير طبيعية منها، وهي من العلامات التي تستحق التقييم الطبي.',
    anatomy_lymph: 'العقد اللمفاوية',
    anatomy_lymph_desc: 'العقد اللمفاوية في منطقة الإبط تلعب دورًا مهمًا في تقييم مرحلة سرطان الثدي وانتشاره.',

    // Warning signs page
    signs_title: 'علامات تستحق الانتباه',
    signs_sub: 'انقري على كل منطقة لمعرفة المزيد',
    signs_note_title: 'ملاحظة مهمة',
    signs_note: 'هذه العلامات لا تعني بالضرورة وجود سرطان. كثيرٌ من هذه التغيرات قد يكون لأسباب حميدة. لكنها جميعًا تستحق التقييم الطبي.',
    signs_cta: 'لاحظتِ تغيرًا جديدًا؟ لا تنتظري حتى يختفي من تلقاء نفسه — تحدثي مع الطبيب أو مقدّم الرعاية الصحية.',
    sign1_title: 'كتلة جديدة',
    sign1_desc: 'كتلة جديدة في الثدي أو الإبط — سواء كانت مؤلمة أو غير مؤلمة — تستحق التقييم الطبي.',
    sign1_why: 'رغم أن معظم الكتل حميدة، فإن الكتلة الجديدة وغير المعتادة تستحق دائمًا فحصًا طبيًا.',
    sign2_title: 'تغير في الحجم أو الشكل',
    sign2_desc: 'أي تغير ملحوظ في حجم الثدي أو شكله قد يستحق الانتباه.',
    sign2_why: 'قد يكون التغير طبيعيًا في بعض الأحيان، لكن التغيرات المفاجئة أو غير المبررة تستحق المراجعة.',
    sign3_title: 'تغيرات في الجلد',
    sign3_desc: 'تغيرات في جلد الثدي مثل الاحمرار أو التجعد أو ظهور نسيج يشبه قشر البرتقال.',
    sign3_why: 'بعض هذه التغيرات قد تكون مرتبطة بحالات تستحق التقييم الطبي.',
    sign4_title: 'انقلاب الحلمة',
    sign4_desc: 'انقلاب حديث للحلمة إلى الداخل عندما لم تكن كذلك من قبل.',
    sign4_why: 'هذا التغير قد يكون طبيعيًا لدى بعض النساء منذ البداية، لكن إذا كان جديدًا فهو يستحق المراجعة.',
    sign5_title: 'إفرازات من الحلمة',
    sign5_desc: 'ظهور إفرازات من الحلمة بدون رضاعة طبيعية، خاصةً إذا كانت دموية أو شفافة.',
    sign5_why: 'معظم الإفرازات لها أسباب حميدة، لكن بعض أنواعها قد تستدعي التقييم.',
    sign6_title: 'تغيرات في منطقة الإبط',
    sign6_desc: 'ظهور كتلة أو تضخم في منطقة الإبط قد يكون مرتبطًا بالعقد اللمفاوية.',
    sign6_why: 'يُشكّل الإبط جزءًا من منظومة الفحص وتقييم أي تغير في الثدي.',

    // Early detection
    detection_title: 'الكشف المبكر قد يغيّر الرحلة',
    detection_sub: 'قد لا يسبب سرطان الثدي أعراضًا واضحة في مراحله المبكرة، ولذلك فإن الالتزام ببرامج الفحص المناسبة للعمر ومستوى الخطورة مهم.',
    detection_timeline_title: 'رحلة الكشف',
    detection_cta: 'هل حان وقت فحصك؟',
    detection_sub_cta: 'تعرّفي على الفحص المناسب لك',
    detection_note: 'توصيات الفحص تختلف حسب العمر والتاريخ الصحي الشخصي والعائلي وعوامل الخطورة. تحدثي مع مقدّم الرعاية الصحية للحصول على توصية مناسبة لك.',
    timeline_t1: 'قبل ظهور الأعراض',
    timeline_t1_desc: 'الالتزام بالفحص الدوري يمكّن من اكتشاف أي تغير في مرحلة مبكرة.',
    timeline_t2: 'الكشف',
    timeline_t2_desc: 'الماموغرام وغيره من أدوات الفحص تتيح رؤية ما لا يُرى بالعين المجردة.',
    timeline_t3: 'التشخيص',
    timeline_t3_desc: 'عند اكتشاف تغير، تُجرى فحوصات إضافية لتأكيد التشخيص وتحديد نوعه.',
    timeline_t4: 'العلاج',
    timeline_t4_desc: 'يتحدد نوع العلاج بناءً على نوع السرطان ومرحلته والحالة الصحية.',
    timeline_t5: 'المتابعة',
    timeline_t5_desc: 'المتابعة الدورية بعد العلاج جزء مهم من رحلة التعافي.',

    // Mammogram
    mammo_title: 'الماموغرام: ماذا يحدث؟',
    mammo_sub: 'الماموغرام هو تصوير بالأشعة السينية بجرعة منخفضة ويُستخدم للتحري والتشخيص.',
    mammo_step1_title: 'الاستعداد',
    mammo_step1_desc: 'يُنصح بتجنب استخدام مزيل العرق أو الكريمات يوم التصوير. أخبري الطبيب بأي أعراض أو تاريخ صحي مهم.',
    mammo_step2_title: 'وضع الثدي',
    mammo_step2_desc: 'يتم وضع الثدي بين لوحتين خاصتين لضغطه وتسطيحه للحصول على صورة واضحة وبأقل جرعة إشعاعية ممكنة.',
    mammo_step3_title: 'التصوير',
    mammo_step3_desc: 'تستغرق عملية التصوير لكل ثدي ثوانٍ معدودة. قد تشعرين بضغط مؤقت خلال هذه الثوانٍ.',
    mammo_step4_title: 'قراءة النتائج',
    mammo_step4_desc: 'يقرأ الطبيب المختص الصور ويحلّلها. إذا احتاج الأمر إلى فحص إضافي فهذا لا يعني بالضرورة وجود مشكلة.',
    mammo_reassure: 'قد تشعر المرأة بضغط أثناء التصوير، لكنه يستمر لثوانٍ ويساعد على الحصول على صورة واضحة.',

    // Saudi Arabia
    saudi_title: 'سرطان الثدي في السعودية',
    saudi_main: 'في المملكة، يُعد سرطان الثدي أكثر السرطانات شيوعًا بين النساء.',
    saudi_journey_title: 'رحلة الوعي',
    saudi_j1: 'التوعية',
    saudi_j2: 'زيادة المعرفة',
    saudi_j3: 'الإقبال على الفحص',
    saudi_j4: 'الاكتشاف المبكر',
    saudi_j5: 'فرص علاج أفضل',
    saudi_efforts_title: 'جهود التوعية في المملكة',
    saudi_efforts: 'تُجري وزارة الصحة السعودية حملات وطنية للتوعية بسرطان الثدي والكشف المبكر، مع التشجيع على الفحص الدوري المبكر. وهذا المحتوى تعليمي يهدف إلى رفع الوعي العام.',
    saudi_stat_label: 'المصدر: وزارة الصحة السعودية',
    saudi_cta: 'اعرفي أين يمكنك الحصول على خدمات الكشف المبكر',
    saudi_educational_note: 'يُقدَّم هذا المحتوى لأغراض تعليمية وتوعوية. للحصول على معلومات دقيقة وحديثة، يُرجى الرجوع إلى وزارة الصحة السعودية.',

    // Myth vs Fact
    myth_title: 'خرافة أم حقيقة؟',
    myth_sub: 'اختبري معرفتك بضغطة واحدة',
    myth_btn: 'خرافة',
    fact_btn: 'حقيقة',
    myth_correct: 'إجابة صحيحة! 🎉',
    myth_wrong: 'ليست الإجابة الصحيحة',
    myth_next: 'السؤال التالي',
    myth_score_title: 'نتيجتك',
    myth_score_out: 'من',
    myth_restart: 'ابدئي من جديد',

    // Risk factors
    risk_title: 'ما الذي قد يزيد من خطر الإصابة؟',
    risk_note: 'وجود عامل خطر لا يعني أن الشخص سيصاب بسرطان الثدي، وغياب عوامل الخطر لا يعني استحالة الإصابة.',
    risk1: 'التقدم في العمر',
    risk1_desc: 'يزداد خطر الإصابة بسرطان الثدي مع التقدم في العمر.',
    risk2: 'التاريخ العائلي',
    risk2_desc: 'وجود حالات سرطان الثدي في العائلة قد يزيد من احتمالية الإصابة.',
    risk3: 'بعض الطفرات الجينية',
    risk3_desc: 'طفرات في جينات معينة مثل BRCA1 و BRCA2 قد ترتبط بزيادة المخاطر.',
    risk4: 'السمنة',
    risk4_desc: 'قد يرتبط الوزن الزائد بعد انقطاع الطمث بزيادة طفيفة في الخطر.',
    risk5: 'قلة النشاط البدني',
    risk5_desc: 'النشاط البدني المنتظم يُعدّ من العادات الصحية المفيدة بشكل عام.',
    risk6: 'بعض العوامل الهرمونية',
    risk6_desc: 'بعض العوامل الهرمونية والإنجابية قد تؤثر على مستوى الخطر.',
    risk7: 'التعرض السابق للإشعاع',
    risk7_desc: 'التعرض لإشعاع العلاج في منطقة الصدر في وقت سابق من الحياة قد يزيد من الخطر.',

    // Prevention wheel
    prev_title: 'خطوات لصحة أفضل',
    prev_sub: 'يمكن لبعض العادات الصحية أن تساعد في تقليل بعض عوامل الخطورة.',
    prev1: 'النشاط البدني',
    prev1_desc: 'ممارسة النشاط البدني المنتظم مفيدة للصحة العامة ولتقليل بعض عوامل الخطورة.',
    prev2: 'الوزن الصحي',
    prev2_desc: 'الحفاظ على وزن صحي يُعدّ من العادات الصحية الإيجابية.',
    prev3: 'التغذية المتوازنة',
    prev3_desc: 'تناول نظام غذائي متوازن غني بالفواكه والخضروات يدعم الصحة العامة.',
    prev4: 'تجنب التدخين',
    prev4_desc: 'تجنب التدخين وتقليل استهلاك الكحول مفيد للصحة العامة.',
    prev5: 'الرضاعة الطبيعية',
    prev5_desc: 'الرضاعة الطبيعية عند ملاءمتها قد تكون لها فوائد صحية متعددة.',
    prev6: 'الفحوصات الدورية',
    prev6_desc: 'الالتزام بالفحوصات الدورية المناسبة للعمر ومستوى الخطورة أمر مهم.',

    // Journey
    journey_title: 'من التشخيص إلى التعافي',
    journey_sub: 'لا توجد رحلة واحدة تناسب الجميع. يحدد الفريق الطبي الخطة المناسبة لكل حالة.',
    journey_s1: 'الاكتشاف',
    journey_s1_desc: 'قد يبدأ الاكتشاف بملاحظة تغير في الثدي، أو من خلال فحص روتيني أو ماموغرام.',
    journey_s2: 'التشخيص',
    journey_s2_desc: 'تُجرى فحوصات للتأكد من التشخيص، قد تشمل الماموغرام والموجات فوق الصوتية والخزعة.',
    journey_s3: 'تحديد المرحلة',
    journey_s3_desc: 'يُحدَّد نوع السرطان ومرحلته ليساعد في اختيار خطة العلاج الأنسب.',
    journey_s4: 'اختيار العلاج',
    journey_s4_desc: 'قد يشمل العلاج الجراحة والإشعاع والعلاج الكيميائي والهرموني والمستهدف حسب الحالة.',
    journey_s5: 'المتابعة',
    journey_s5_desc: 'متابعة دورية مع الفريق الطبي لمراقبة الاستجابة للعلاج وتعديل الخطة عند الحاجة.',
    journey_s6: 'الحياة بعد العلاج',
    journey_s6_desc: 'يستمر الدعم الطبي والنفسي بعد انتهاء العلاج لمساعدة المريضة على استعادة جودة حياتها.',

    // Reconstruction
    recon_title: 'إعادة بناء الثدي',
    recon_sub: 'إعادة بناء الثدي هي عملية جراحية تستهدف استعادة شكل الثدي بعد استئصاله كليًا أو جزئيًا.',
    recon_when_title: 'متى يمكن إجراؤها؟',
    recon_when: 'يمكن إجراء إعادة البناء في نفس وقت استئصال الثدي (فورية) أو بعد اكتمال العلاجات الأخرى (مؤجلة). يعتمد التوقيت على الحالة الفردية وخطة العلاج.',
    recon_options_title: 'الخيارات المتاحة',
    recon_option1: 'إعادة البناء بالأنسجة الذاتية',
    recon_option1_detail: 'تستخدم أنسجة المريضة الخاصة من مناطق أخرى من الجسم كالبطن أو الظهر. تُعطي نتيجة طبيعية ودائمة.',
    recon_option2: 'إعادة البناء باستخدام الغرسات',
    recon_option2_detail: 'تستخدم غرسات الثدي الطبية الصناعية. قد تُجرى على مرحلة واحدة أو مرحلتين.',
    recon_note: 'يُحدَّد الخيار الأنسب بناءً على الحالة الصحية للمريضة وخطة العلاج ورغبتها بعد مناقشة مفصّلة مع الفريق الطبي.',
    recon_cta: 'اكتشفي خيارات إعادة بناء الثدي',

    // Support
    support_title: 'لستِ وحدك',
    support_sub: 'الدعم لا يعالج المرض، لكنه قد يجعل رحلة العلاج أقل وحدة وأكثر احتمالًا.',
    support_how_title: 'كيف يمكنني دعم شخص عزيز؟',
    support_tip1: 'استمعي دون إصدار أحكام',
    support_tip2: 'ساعدي في المواعيد أو المهام اليومية',
    support_tip3: 'احترمي رغبتها في الحديث أو الصمت',
    support_tip4: 'اسأليها كيف يمكنك المساعدة',
    support_tip5: 'تجنبي إعطاء نصائح طبية غير موثوقة',
    support_psych: 'الدعم النفسي',
    support_psych_desc: 'الدعم العاطفي والنفسي المتخصص جزء مهم من رحلة العلاج والتعافي.',
    support_family: 'العائلة',
    support_family_desc: 'العائلة هي الركيزة الأساسية في رحلة العلاج والتعافي.',
    support_friends: 'الأصدقاء',
    support_friends_desc: 'الأصدقاء يمكنهم تقديم دعم عملي وعاطفي لا يُقدَّر بثمن.',
    support_medical: 'الفريق الطبي',
    support_medical_desc: 'الفريق الطبي المتخصص يرافق المريضة في كل مراحل العلاج.',
    support_community: 'المجتمع',
    support_community_desc: 'مجموعات الدعم والمجتمع يمكن أن تكون مصدرًا كبيرًا للطمأنينة والأمل.',

    // FAQ
    faq_title: 'أسئلة شائعة',
    faq1_q: 'هل سرطان الثدي يصيب الرجال؟',
    faq1_a: 'نعم، يمكن أن يصيب سرطان الثدي الرجال، وإن كان أقل شيوعًا بكثير مقارنة بالنساء. يُشكّل سرطان الثدي لدى الرجال نسبة صغيرة من إجمالي الحالات. وتشمل العلامات التي يجب الانتباه إليها أي كتلة أو تغير في منطقة الثدي.',
    faq2_q: 'هل كل كتلة في الثدي تعني سرطانًا؟',
    faq2_a: 'لا، معظم كتل الثدي حميدة وغير سرطانية. لكن أي كتلة جديدة أو غير معتادة تستحق دائمًا التقييم الطبي للتأكد من طبيعتها.',
    faq3_q: 'هل يمكن أن يحدث سرطان الثدي دون أعراض؟',
    faq3_a: 'نعم، قد لا يسبب سرطان الثدي أعراضًا واضحة في مراحله المبكرة، وهذا هو أحد أهم أسباب التأكيد على أهمية الفحص الدوري حتى في غياب الأعراض.',
    faq4_q: 'ما هو الماموغرام؟',
    faq4_a: 'الماموغرام هو تصوير بالأشعة السينية بجرعة منخفضة يستخدم للكشف المبكر عن أي تغيرات في أنسجة الثدي. يُستخدم للتحري الدوري والتشخيص عند وجود أعراض.',
    faq5_q: 'هل الماموغرام مؤلم؟',
    faq5_a: 'قد تشعر بعض النساء بضغط أو انزعاج مؤقت أثناء التصوير، لكنه يستمر لثوانٍ معدودة. يمكن إخبار الفني بأي انزعاج تشعرين به.',
    faq6_q: 'متى أحتاج إلى استشارة الطبيب؟',
    faq6_a: 'إذا لاحظتِ أي تغير جديد أو غير معتاد في الثدي أو الإبط مثل كتلة جديدة، تغير في الحجم أو الشكل، تغيرات في الجلد، تغير في الحلمة، أو إفرازات، يُنصح بطلب التقييم الطبي. لا تنتظري حتى يختفي التغير وحده.',
    faq7_q: 'هل وجود تاريخ عائلي يعني أنني سأصاب بالمرض؟',
    faq7_a: 'لا، وجود تاريخ عائلي يزيد من احتمالية الإصابة لكنه لا يعني الإصابة حتمًا. كما أن معظم حالات سرطان الثدي تحدث لدى أشخاص لا يوجد لديهم تاريخ عائلي للمرض.',
    faq8_q: 'هل يمكن علاج سرطان الثدي؟',
    faq8_a: 'نعم، سرطان الثدي يمكن علاجه، خاصةً عند اكتشافه مبكرًا. تختلف خيارات وفرص العلاج بحسب نوع السرطان ومرحلته والحالة الصحية للمريضة.',
    faq9_q: 'ما هي إعادة بناء الثدي؟',
    faq9_a: 'إعادة بناء الثدي هي عملية جراحية تهدف إلى استعادة شكل الثدي بعد إجراء استئصال كلي أو جزئي. يمكن إجراؤها في نفس وقت الاستئصال أو لاحقًا، وتشمل الخيارات استخدام أنسجة الجسم الذاتية أو الغرسات الطبية.',

    // Quiz
    quiz_title: 'اختبري معلوماتك',
    quiz_disclaimer: 'هذا الاختبار للتوعية فقط ولا يُستخدم لتشخيص سرطان الثدي.',
    quiz_next: 'السؤال التالي',
    quiz_finish: 'اعرفي نتيجتك',
    quiz_restart: 'أعيدي الاختبار',
    quiz_excellent: 'أحسنتِ! 🎉',
    quiz_learned: 'معلومة جديدة اكتسبتِها اليوم 💗',
    quiz_score: 'نتيجتك',
    quiz_out_of: 'من',
    quiz_correct: 'إجابة صحيحة! ✓',
    quiz_wrong: 'إجابة خاطئة',
    quiz_answer_reveal: 'الإجابة الصحيحة:',

    // CTA
    cta_headline: 'معرفة اليوم قد تصنع فرقًا غدًا.',
    cta_sub: 'تعرّفي، افحصي، وشاركي الوعي.',
    cta_btn1: 'تعرّفي على الكشف المبكر',
    cta_btn2: 'شاركي التوعية',
    cta_share_msg: 'الوعي بسرطان الثدي — معرفة اليوم قد تصنع فرقًا غدًا. #أكتوبر_وردي',

    // Footer
    footer_title: 'التوعية بسرطان الثدي',
    footer_tagline: 'الوعي بداية الأمل',
    footer_home: 'الرئيسية',
    footer_learn: 'اعرفي أكثر',
    footer_detection: 'الكشف المبكر',
    footer_faq: 'الأسئلة الشائعة',
    footer_sources: 'المصادر',
    footer_disclaimer: 'المعلومات الصحية مبنية على مصادر صحية موثوقة، ويجب الرجوع إلى الجهات الصحية الرسمية والطبيب للحصول على توصيات شخصية.',
    footer_moh: 'وزارة الصحة السعودية',
    footer_who: 'منظمة الصحة العالمية',
    footer_rights: 'للأغراض التوعوية والتثقيفية فقط',

    // Medical disclaimer
    disclaimer: 'هذا الموقع للتوعية والتثقيف الصحي ولا يُغني عن استشارة الطبيب أو مقدم الرعاية الصحية. عند ملاحظة تغير جديد أو غير معتاد في الثدي، يُنصح بطلب التقييم الطبي.',

    // General
    back: 'رجوع للرئيسية',
    learn_more: 'اعرفي أكثر',
    close: 'إغلاق',
  },

  en: {
    // Navigation
    nav_home: 'Home',
    nav_learn: 'Learn More',
    nav_signs: 'Warning Signs',
    nav_detection: 'Early Detection',
    nav_prevention: 'Prevention',
    nav_journey: 'Treatment Journey',
    nav_reconstruction: 'Breast Reconstruction',
    nav_saudi: 'In Saudi Arabia',
    nav_faq: 'FAQs',
    nav_start: 'Start Now',
    nav_lang: 'العربية',

    // Hero
    hero_badge: 'October | Breast Cancer Awareness Month',
    hero_headline_1: 'Awareness is',
    hero_headline_2: 'the Beginning of Hope',
    hero_sub: 'Breast cancer is one of the most common cancers among women in Saudi Arabia. Early detection can make a significant difference in the treatment journey.',
    hero_cta1: 'Learn About Early Detection',
    hero_cta2: 'Explore Warning Signs',
    hero_fact1: 'Early detection makes a difference',
    hero_fact2: 'Awareness starts with knowledge',
    hero_fact3: 'You are not alone',

    // Explore section
    explore_title: 'Where Do We Begin?',
    explore_sub: 'Choose the topic you want to learn more about',
    explore_read_more: 'Learn More',

    // Explore cards
    card1_emoji: '🎀',
    card1_title: 'What is Breast Cancer?',
    card1_desc: 'Understanding the disease simply and clearly',
    card2_emoji: '🔎',
    card2_title: 'Warning Signs',
    card2_desc: 'Learn about changes that may deserve evaluation',
    card3_emoji: '🩷',
    card3_title: 'Early Detection',
    card3_desc: 'Why timing matters in diagnosis',
    card4_emoji: '🌿',
    card4_title: 'Reducing Risk Factors',
    card4_desc: 'Healthy habits that may help reduce risk',
    card5_emoji: '🤍',
    card5_title: 'Treatment & Recovery Journey',
    card5_desc: 'From diagnosis to life after treatment',
    card6_emoji: '🌸',
    card6_title: 'Breast Reconstruction',
    card6_desc: 'Reconstruction options after surgery',

    // What is breast cancer page
    whatIs_title: 'What is Breast Cancer?',
    whatIs_body: 'Breast cancer is the abnormal growth of breast cells. It may begin in breast tissue, and as the disease progresses, it can spread to lymph nodes or other organs.',
    whatIs_body2: 'Breast cancer is one of the most common cancers worldwide among women, including in Saudi Arabia. It can also affect men, though less commonly.',
    whatIs_anatomy_title: 'Understanding Breast Anatomy',
    whatIs_anatomy_sub: 'Click on each area to learn more',
    whatIs_note: 'The presence of a lump does not necessarily mean cancer, but any new or unusual change deserves medical evaluation.',
    anatomy_tissue: 'Breast Tissue',
    anatomy_tissue_desc: 'Breast tissue consists of mammary glands, fatty tissue, and connective tissue. Most types of breast cancer begin in these tissues.',
    anatomy_ducts: 'Ducts',
    anatomy_ducts_desc: 'Ducts are the channels through which milk travels from the glands to the nipple. Ductal Carcinoma is one of the most common types of breast cancer.',
    anatomy_nipple: 'Nipple',
    anatomy_nipple_desc: 'Changes in the nipple such as inversion or unusual discharge are among the signs that deserve medical evaluation.',
    anatomy_lymph: 'Lymph Nodes',
    anatomy_lymph_desc: 'Lymph nodes in the armpit area play an important role in evaluating the stage of breast cancer and its spread.',

    // Warning signs page
    signs_title: 'Warning Signs Worth Noticing',
    signs_sub: 'Click on each area to learn more',
    signs_note_title: 'Important Note',
    signs_note: 'These signs do not necessarily mean cancer. Many of these changes may have benign causes. But they all deserve medical evaluation.',
    signs_cta: "Noticed a new change? Don't wait for it to go away on its own — speak with your doctor or healthcare provider.",
    sign1_title: 'A New Lump',
    sign1_desc: 'A new lump in the breast or armpit — whether painful or painless — deserves medical evaluation.',
    sign1_why: 'While most lumps are benign, any new and unusual lump always deserves a medical check.',
    sign2_title: 'Change in Size or Shape',
    sign2_desc: 'Any noticeable change in the size or shape of the breast may be worth attention.',
    sign2_why: 'Changes can sometimes be normal, but sudden or unexplained changes deserve a check.',
    sign3_title: 'Skin Changes',
    sign3_desc: 'Changes in breast skin such as redness, dimpling, or tissue resembling an orange peel.',
    sign3_why: 'Some of these changes may be associated with conditions that deserve medical evaluation.',
    sign4_title: 'Nipple Inversion',
    sign4_desc: 'Recent inversion of the nipple inward when it was not that way before.',
    sign4_why: "This change may be normal in some women from the start, but if it's new, it deserves attention.",
    sign5_title: 'Nipple Discharge',
    sign5_desc: 'Nipple discharge without breastfeeding, especially if bloody or clear.',
    sign5_why: 'Most discharge has benign causes, but some types may require evaluation.',
    sign6_title: 'Changes in the Armpit',
    sign6_desc: 'A lump or swelling in the armpit area may be related to lymph nodes.',
    sign6_why: 'The armpit is part of the examination and evaluation of any breast change.',

    // Early detection
    detection_title: 'Early Detection Can Change the Journey',
    detection_sub: 'Breast cancer may not cause obvious symptoms in its early stages. This is why adhering to age and risk-appropriate screening programs is important.',
    detection_timeline_title: 'The Detection Journey',
    detection_cta: 'Is it time for your screening?',
    detection_sub_cta: 'Find the right screening for you',
    detection_note: 'Screening recommendations vary by age, personal health history, family history, and risk factors. Talk to your healthcare provider for a recommendation tailored to you.',
    timeline_t1: 'Before Symptoms Appear',
    timeline_t1_desc: 'Regular screening allows any changes to be detected at an early stage.',
    timeline_t2: 'Screening',
    timeline_t2_desc: 'Mammograms and other screening tools allow visualization of what cannot be seen with the naked eye.',
    timeline_t3: 'Diagnosis',
    timeline_t3_desc: 'When a change is detected, additional tests are performed to confirm the diagnosis and determine its type.',
    timeline_t4: 'Treatment',
    timeline_t4_desc: 'Treatment type is determined based on cancer type, stage, and health status.',
    timeline_t5: 'Follow-up',
    timeline_t5_desc: 'Regular follow-up after treatment is an important part of the recovery journey.',

    // Mammogram
    mammo_title: 'Mammogram: What Happens?',
    mammo_sub: 'A mammogram is a low-dose X-ray imaging used for screening and diagnosis.',
    mammo_step1_title: 'Preparation',
    mammo_step1_desc: 'Avoid using deodorant or creams on the day of imaging. Tell your doctor about any symptoms or important health history.',
    mammo_step2_title: 'Breast Positioning',
    mammo_step2_desc: 'The breast is placed between two special plates to compress and flatten it for a clear image with the lowest possible radiation dose.',
    mammo_step3_title: 'Imaging',
    mammo_step3_desc: 'The imaging process for each breast takes only a few seconds. You may feel temporary pressure during these seconds.',
    mammo_step4_title: 'Reading Results',
    mammo_step4_desc: 'A specialist reads and analyzes the images. If additional testing is needed, it does not necessarily mean there is a problem.',
    mammo_reassure: 'A woman may feel pressure during imaging, but it lasts only seconds and helps obtain a clear image.',

    // Saudi Arabia
    saudi_title: 'Breast Cancer in Saudi Arabia',
    saudi_main: 'In Saudi Arabia, breast cancer is the most common cancer among women.',
    saudi_journey_title: 'The Awareness Journey',
    saudi_j1: 'Awareness',
    saudi_j2: 'Increased Knowledge',
    saudi_j3: 'Uptake of Screening',
    saudi_j4: 'Early Detection',
    saudi_j5: 'Better Treatment Outcomes',
    saudi_efforts_title: 'Awareness Efforts in the Kingdom',
    saudi_efforts: 'The Saudi Ministry of Health conducts national breast cancer awareness and early screening campaigns, encouraging regular early screening. This content is educational and aims to raise general awareness.',
    saudi_stat_label: 'Source: Saudi Ministry of Health',
    saudi_cta: 'Find where you can access early detection services',
    saudi_educational_note: 'This content is presented for educational and awareness purposes. For accurate and up-to-date information, please refer to the Saudi Ministry of Health.',

    // Myth vs Fact
    myth_title: 'Myth or Fact?',
    myth_sub: 'Test your knowledge with one click',
    myth_btn: 'Myth',
    fact_btn: 'Fact',
    myth_correct: 'Correct! 🎉',
    myth_wrong: 'Not quite right',
    myth_next: 'Next Question',
    myth_score_title: 'Your Score',
    myth_score_out: 'out of',
    myth_restart: 'Start Over',

    // Risk factors
    risk_title: 'What May Increase the Risk?',
    risk_note: 'Having a risk factor does not mean a person will develop breast cancer, and the absence of risk factors does not mean it is impossible.',
    risk1: 'Age',
    risk1_desc: 'The risk of breast cancer increases with age.',
    risk2: 'Family History',
    risk2_desc: 'A family history of breast cancer may increase the likelihood of developing it.',
    risk3: 'Certain Genetic Mutations',
    risk3_desc: 'Mutations in certain genes such as BRCA1 and BRCA2 may be associated with increased risk.',
    risk4: 'Obesity',
    risk4_desc: 'Being overweight after menopause may be associated with a slight increase in risk.',
    risk5: 'Physical Inactivity',
    risk5_desc: 'Regular physical activity is considered a beneficial healthy habit in general.',
    risk6: 'Certain Hormonal Factors',
    risk6_desc: 'Some hormonal and reproductive factors may affect the level of risk.',
    risk7: 'Previous Radiation Exposure',
    risk7_desc: 'Previous radiation treatment to the chest area earlier in life may increase the risk.',

    // Prevention wheel
    prev_title: 'Steps for Better Health',
    prev_sub: 'Some healthy habits can help reduce certain risk factors.',
    prev1: 'Physical Activity',
    prev1_desc: 'Regular physical activity is beneficial for general health and reducing some risk factors.',
    prev2: 'Healthy Weight',
    prev2_desc: 'Maintaining a healthy weight is a positive healthy habit.',
    prev3: 'Balanced Nutrition',
    prev3_desc: 'A balanced diet rich in fruits and vegetables supports overall health.',
    prev4: 'Avoid Smoking',
    prev4_desc: 'Avoiding smoking and reducing alcohol consumption is beneficial for general health.',
    prev5: 'Breastfeeding',
    prev5_desc: 'Breastfeeding when appropriate may have multiple health benefits.',
    prev6: 'Regular Screenings',
    prev6_desc: 'Adhering to age and risk-appropriate regular screenings is important.',

    // Journey
    journey_title: 'From Diagnosis to Recovery',
    journey_sub: 'There is no one journey that fits everyone. The medical team determines the appropriate plan for each case.',
    journey_s1: 'Discovery',
    journey_s1_desc: 'Discovery may begin with noticing a change in the breast, or through a routine examination or mammogram.',
    journey_s2: 'Diagnosis',
    journey_s2_desc: 'Tests are performed to confirm the diagnosis, which may include mammogram, ultrasound, and biopsy.',
    journey_s3: 'Staging',
    journey_s3_desc: 'The type and stage of cancer is determined to help choose the most appropriate treatment plan.',
    journey_s4: 'Treatment',
    journey_s4_desc: 'Treatment may include surgery, radiation, chemotherapy, hormonal therapy, and targeted therapy depending on the case.',
    journey_s5: 'Follow-up',
    journey_s5_desc: 'Regular follow-up with the medical team to monitor treatment response and adjust the plan when needed.',
    journey_s6: 'Life After Treatment',
    journey_s6_desc: 'Medical and psychological support continues after treatment ends to help the patient restore quality of life.',

    // Reconstruction
    recon_title: 'Breast Reconstruction',
    recon_sub: 'Breast reconstruction is a surgical procedure aimed at restoring breast shape after a total or partial mastectomy.',
    recon_when_title: 'When Can It Be Done?',
    recon_when: 'Reconstruction can be performed at the same time as mastectomy (immediate) or after completion of other treatments (delayed). The timing depends on the individual case and treatment plan.',
    recon_options_title: 'Available Options',
    recon_option1: 'Reconstruction Using Own Tissue',
    recon_option1_detail: "Uses the patient's own tissue from other areas of the body such as the abdomen or back. Provides a natural and lasting result.",
    recon_option2: 'Reconstruction Using Implants',
    recon_option2_detail: 'Uses artificial medical breast implants. May be performed in one or two stages.',
    recon_note: 'The most appropriate option is determined based on the health condition of the patient, the treatment plan, and her preference after a detailed discussion with the medical team.',
    recon_cta: 'Explore Breast Reconstruction Options',

    // Support
    support_title: 'You Are Not Alone',
    support_sub: 'Support does not cure the disease, but it can make the treatment journey less lonely and more bearable.',
    support_how_title: 'How Can I Support a Loved One?',
    support_tip1: 'Listen without judgment',
    support_tip2: 'Help with appointments or daily tasks',
    support_tip3: 'Respect their wish to talk or be silent',
    support_tip4: 'Ask how you can help',
    support_tip5: 'Avoid giving unreliable medical advice',
    support_psych: 'Psychological Support',
    support_psych_desc: 'Specialized emotional and psychological support is an important part of the treatment and recovery journey.',
    support_family: 'Family',
    support_family_desc: 'Family is the primary pillar in the treatment and recovery journey.',
    support_friends: 'Friends',
    support_friends_desc: 'Friends can provide invaluable practical and emotional support.',
    support_medical: 'Medical Team',
    support_medical_desc: 'The specialized medical team accompanies the patient through all stages of treatment.',
    support_community: 'Community',
    support_community_desc: 'Support groups and community can be a great source of reassurance and hope.',

    // FAQ
    faq_title: 'Frequently Asked Questions',
    faq1_q: 'Can breast cancer affect men?',
    faq1_a: 'Yes, breast cancer can affect men, though it is far less common than in women. Male breast cancer represents a small percentage of total cases. Signs to watch for include any lump or change in the breast area.',
    faq2_q: 'Does every breast lump mean cancer?',
    faq2_a: 'No, most breast lumps are benign and non-cancerous. But any new or unusual lump always deserves medical evaluation to determine its nature.',
    faq3_q: 'Can breast cancer occur without symptoms?',
    faq3_a: 'Yes, breast cancer may not cause obvious symptoms in its early stages. This is one of the most important reasons for emphasizing regular screening even in the absence of symptoms.',
    faq4_q: 'What is a mammogram?',
    faq4_a: 'A mammogram is a low-dose X-ray imaging used for early detection of any changes in breast tissue. It is used for routine screening and diagnosis when symptoms are present.',
    faq5_q: 'Is a mammogram painful?',
    faq5_a: 'Some women may feel pressure or temporary discomfort during imaging, but it lasts only a few seconds. You can tell the technician about any discomfort you feel.',
    faq6_q: 'When do I need to consult a doctor?',
    faq6_a: 'If you notice any new or unusual change in the breast or armpit such as a new lump, change in size or shape, skin changes, nipple change, or discharge, it is recommended to seek medical evaluation. Do not wait for the change to disappear on its own.',
    faq7_q: 'Does having a family history mean I will develop the disease?',
    faq7_a: 'No, having a family history increases the likelihood but does not mean definite development. Also, most breast cancer cases occur in people with no family history of the disease.',
    faq8_q: 'Can breast cancer be treated?',
    faq8_a: 'Yes, breast cancer can be treated, especially when detected early. Treatment options and outcomes vary depending on the type and stage of cancer and the health condition of the patient.',
    faq9_q: 'What is breast reconstruction?',
    faq9_a: 'Breast reconstruction is a surgical procedure aimed at restoring breast shape after a total or partial mastectomy. It can be performed at the same time as the mastectomy or later, and options include using the body\'s own tissue or medical implants.',

    // Quiz
    quiz_title: 'Test Your Knowledge',
    quiz_disclaimer: 'This quiz is for awareness only and is not used to diagnose breast cancer.',
    quiz_next: 'Next Question',
    quiz_finish: 'See Your Results',
    quiz_restart: 'Retake Quiz',
    quiz_excellent: 'Well Done! 🎉',
    quiz_learned: 'You learned something new today 💗',
    quiz_score: 'Your Score',
    quiz_out_of: 'out of',
    quiz_correct: 'Correct! ✓',
    quiz_wrong: 'Incorrect',
    quiz_answer_reveal: 'The correct answer:',

    // CTA
    cta_headline: 'Knowledge today can make a difference tomorrow.',
    cta_sub: 'Learn, screen, and spread awareness.',
    cta_btn1: 'Learn About Early Detection',
    cta_btn2: 'Share Awareness',
    cta_share_msg: 'Breast Cancer Awareness — Knowledge today can make a difference tomorrow. #PinkOctober',

    // Footer
    footer_title: 'Breast Cancer Awareness',
    footer_tagline: 'Awareness is the beginning of hope',
    footer_home: 'Home',
    footer_learn: 'Learn More',
    footer_detection: 'Early Detection',
    footer_faq: 'FAQs',
    footer_sources: 'Sources',
    footer_disclaimer: 'Health information is based on trusted medical sources. Please refer to official health authorities and your doctor for personalized recommendations.',
    footer_moh: 'Saudi Ministry of Health',
    footer_who: 'World Health Organization',
    footer_rights: 'For awareness and educational purposes only',

    // Medical disclaimer
    disclaimer: 'This website is for health awareness and education only and does not replace consulting a doctor or healthcare provider. If you notice a new or unusual change in the breast, it is recommended to seek medical evaluation.',

    // General
    back: 'Back to Home',
    learn_more: 'Learn More',
    close: 'Close',
  },
} as const

export type TranslationKey = keyof typeof translations.ar

export const mythQuestions = {
  ar: [
    {
      statement: 'الماموغرام يسبب انتشار سرطان الثدي.',
      isMyth: true,
      explanation: 'الماموغرام أداة للكشف والتحري، وليس سببًا لانتشار السرطان. هو تصوير بالأشعة السينية بجرعة منخفضة آمنة.',
    },
    {
      statement: 'حجم الثدي يؤثر على احتمالية الإصابة بسرطان الثدي.',
      isMyth: true,
      explanation: 'حجم الثدي ليس عاملاً مرتبطاً بخطر الإصابة بسرطان الثدي. يمكن أن يصيب المرض النساء بمختلف أحجام الثدي.',
    },
    {
      statement: 'سرطان الثدي يمكن أن يصيب الرجال أيضًا.',
      isMyth: false,
      explanation: 'نعم، يمكن أن يصيب سرطان الثدي الرجال أيضًا، وإن كان أقل شيوعًا مقارنة بالنساء. وأي تغير في منطقة الثدي لدى الرجل يستحق التقييم الطبي.',
    },
    {
      statement: 'استخدام مزيل العرق يسبب سرطان الثدي.',
      isMyth: true,
      explanation: 'لا توجد أدلة علمية موثوقة تربط بين استخدام مزيل العرق والإصابة بسرطان الثدي.',
    },
    {
      statement: 'كل كتلة في الثدي تعني وجود سرطان.',
      isMyth: true,
      explanation: 'معظم كتل الثدي حميدة وغير سرطانية. لكن أي كتلة جديدة تستحق التقييم الطبي للتأكد من طبيعتها.',
    },
    {
      statement: 'يمكن الإصابة بسرطان الثدي حتى في غياب التاريخ العائلي.',
      isMyth: false,
      explanation: 'نعم، معظم حالات سرطان الثدي تحدث لدى أشخاص لا يوجد لديهم تاريخ عائلي للمرض. التاريخ العائلي يزيد الخطر لكنه ليس شرطًا.',
    },
  ],
  en: [
    {
      statement: 'Mammograms cause breast cancer to spread.',
      isMyth: true,
      explanation: 'A mammogram is a screening and detection tool, not a cause of cancer spread. It is safe low-dose X-ray imaging.',
    },
    {
      statement: 'Breast size affects the likelihood of developing breast cancer.',
      isMyth: true,
      explanation: 'Breast size is not a factor associated with breast cancer risk. The disease can affect women of all breast sizes.',
    },
    {
      statement: 'Breast cancer can also affect men.',
      isMyth: false,
      explanation: 'Yes, breast cancer can also affect men, though it is less common than in women. Any change in a man\'s breast area deserves medical evaluation.',
    },
    {
      statement: 'Using deodorant causes breast cancer.',
      isMyth: true,
      explanation: 'There is no reliable scientific evidence linking deodorant use to breast cancer.',
    },
    {
      statement: 'Every breast lump means cancer.',
      isMyth: true,
      explanation: 'Most breast lumps are benign and non-cancerous. But any new lump deserves medical evaluation to determine its nature.',
    },
    {
      statement: 'You can develop breast cancer even without a family history.',
      isMyth: false,
      explanation: 'Yes, most breast cancer cases occur in people with no family history of the disease. Family history increases the risk but is not a requirement.',
    },
  ],
}

export const quizQuestions = {
  ar: [
    {
      question: 'ما هو أكثر السرطانات شيوعًا بين النساء في المملكة العربية السعودية؟',
      options: ['سرطان الرئة', 'سرطان الثدي', 'سرطان القولون', 'سرطان الجلد'],
      correct: 1,
      explanation: 'يُعدّ سرطان الثدي أكثر السرطانات شيوعًا بين النساء في المملكة العربية السعودية.',
    },
    {
      question: 'ما هي الأداة الأساسية المستخدمة للكشف المبكر عن سرطان الثدي؟',
      options: ['الأشعة المقطعية', 'التصوير بالرنين المغناطيسي', 'الماموغرام', 'الموجات فوق الصوتية'],
      correct: 2,
      explanation: 'الماموغرام هو الأداة الرئيسية المستخدمة للكشف المبكر عن سرطان الثدي.',
    },
    {
      question: 'أيٌّ من التالي قد يكون علامة تستحق التقييم الطبي؟',
      options: ['ألم عابر في الظهر', 'كتلة جديدة في الثدي', 'الشعور بالتعب العام', 'الصداع المتكرر'],
      correct: 1,
      explanation: 'كتلة جديدة في الثدي تستحق دائمًا التقييم الطبي، حتى لو كانت حميدة في أغلب الحالات.',
    },
    {
      question: 'هل يمكن أن يصيب سرطان الثدي الرجال؟',
      options: ['لا، فقط النساء', 'نعم، لكن بنسبة أقل بكثير', 'نعم، بنفس النسبة لدى النساء', 'غير معروف علميًا'],
      correct: 1,
      explanation: 'نعم، يمكن أن يصيب سرطان الثدي الرجال، لكن بنسبة أقل بكثير مقارنة بالنساء.',
    },
    {
      question: 'ما هو الشهر المخصص عالميًا للتوعية بسرطان الثدي؟',
      options: ['سبتمبر', 'نوفمبر', 'أكتوبر', 'يوليو'],
      correct: 2,
      explanation: 'أكتوبر هو شهر التوعية بسرطان الثدي على المستوى العالمي، ويُعرف بـ "الشهر الوردي".',
    },
    {
      question: 'ما الذي تعنيه إعادة بناء الثدي؟',
      options: ['علاج سرطان الثدي بالجراحة', 'استعادة شكل الثدي بعد الاستئصال', 'فحص الثدي بالأشعة', 'علاج التهاب الثدي'],
      correct: 1,
      explanation: 'إعادة بناء الثدي هي عملية جراحية تهدف إلى استعادة شكل الثدي بعد استئصاله كليًا أو جزئيًا.',
    },
    {
      question: 'هل غياب الأعراض يعني عدم وجود سرطان الثدي؟',
      options: ['نعم دائمًا', 'لا، قد يتطور المرض بدون أعراض واضحة', 'أحيانًا فقط', 'لا يوجد إجابة محددة'],
      correct: 1,
      explanation: 'لا، قد يتطور سرطان الثدي في مراحله المبكرة دون أعراض واضحة، وهذا أحد أسباب أهمية الفحص الدوري.',
    },
  ],
  en: [
    {
      question: 'What is the most common cancer among women in Saudi Arabia?',
      options: ['Lung cancer', 'Breast cancer', 'Colon cancer', 'Skin cancer'],
      correct: 1,
      explanation: 'Breast cancer is the most common cancer among women in Saudi Arabia.',
    },
    {
      question: 'What is the primary tool used for early breast cancer detection?',
      options: ['CT scan', 'MRI', 'Mammogram', 'Ultrasound'],
      correct: 2,
      explanation: 'Mammogram is the primary tool used for early detection of breast cancer.',
    },
    {
      question: 'Which of the following may be a sign deserving medical evaluation?',
      options: ['Transient back pain', 'A new breast lump', 'General fatigue', 'Frequent headaches'],
      correct: 1,
      explanation: 'A new breast lump always deserves medical evaluation, even though it is benign in most cases.',
    },
    {
      question: 'Can breast cancer affect men?',
      options: ['No, only women', 'Yes, but much less commonly', 'Yes, at the same rate as women', 'Unknown scientifically'],
      correct: 1,
      explanation: 'Yes, breast cancer can affect men, but much less commonly than women.',
    },
    {
      question: 'Which month is globally dedicated to breast cancer awareness?',
      options: ['September', 'November', 'October', 'July'],
      correct: 2,
      explanation: 'October is the global Breast Cancer Awareness Month, known as "Pink Month".',
    },
    {
      question: 'What does breast reconstruction mean?',
      options: ['Treating breast cancer with surgery', 'Restoring breast shape after mastectomy', 'Imaging the breast with X-ray', 'Treating breast inflammation'],
      correct: 1,
      explanation: 'Breast reconstruction is a surgical procedure aimed at restoring breast shape after a total or partial mastectomy.',
    },
    {
      question: 'Does the absence of symptoms mean there is no breast cancer?',
      options: ['Yes, always', 'No, the disease may develop without obvious symptoms', 'Sometimes only', 'No definitive answer'],
      correct: 1,
      explanation: 'No, breast cancer may develop in its early stages without obvious symptoms, which is one reason why regular screening is important.',
    },
  ],
}
